version: '3'
services:
  sentinel:
    image: hpy253215039/sentinel-dashboard:1.7.1
    container_name: sentinel
    restart: on-failure
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8718:8080"
    environment:
      - JAVA_OPTS=-Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -Djava.security.egd=file:/dev/./urandom -Dcsp.sentinel.api.port=8719
