#基础镜像
#centos版本不要超过宿主机的centos版本
FROM hpy253215039/oraclejdk-skywalking-linux-64:8u221
MAINTAINER      hpy253215039@163.com

RUN mkdir -p /sentinel-dashboard

ADD ./config/ /sentinel-dashboard/
ADD ./jar/1.7.1/ /sentinel-dashboard/

EXPOSE 8080

CMD ["/sentinel-dashboard/scripts/startup-kubernetes.sh"]
